global class GetEnachDataWrapper{
    public cls_dataResponse[] dataResponse;
    public String message;	//All Request Completed Successfully.
    public String transactionid;	//nachSetup21938
    public String status;	//Success
    public Integer statusCode;	//101
    public   class cls_dataResponse {
        public String CUST_ID;	//CU0000000000902518901
        public String IFSC;	//BARB0DBCKOP
        public String BNK_AC_ID;	//16
        public String NACH_STATUS;	//SUCCESS
        public String INSTALL_PERCENT;	//100
        public String TRAN_ID;	//1820700796
        public String NACH_STATUS_DATE;	//2022-06-13 01:08:35.0
        public String AUX_BNK_CODE;	//12
        public String MOBILE_NO1;	//9833999166
        public String COLL_END_AT;	//
        public String STRT_MTH;	//2022-06-13 00:00:00.0
        public String MOBILE_NO2;	//
        public String ACC_NUM;	//99650100006881
        public String MICR;	//400012304
        public String END_MTH;	//2032-07-13 00:00:00.0
        public String REC_CRT_DT;	//
        public String COLL_FRQ;	//MNTH
        public String COLL_MAX_AMT;	//58728
        public String ACCOUNT_HOLDER_NAME;	//Ajay Udayraj Yadav
        public String WI_NAME;	//LOS-00000000009025189-PROCESS
        public String NPCI_BNK_DC_CODE;	//12870
        public String EMAIL_ID2;	//
        public String ACC_TYPE;	//Savings Account
        public String APPLICATION_NO;	//100219025189
        public String BRANCH_NAME;	//CHARKOP
        public String EMAIL_ID1;	//ajayyadav01@gmail.com
        public String NPCI_BNK_NETB_CODE;	//9490
        public String BANK_NAME;	//BANK OF BARODA
        public String COLL_TYPE;	//M
    }
}