public class GetIFSCDetailsAPIWrapper{
    public cls_dataResponse[] dataResponse;
    public String message;	//Request Completed Successfully.
    public String transactionid;	//getIFSCdetails4
    public String status;	//Success
    public Integer statusCode;	//101
    public class cls_dataResponse {
        public String BANKNAME;	//LATUR DISTRICT CENTRAL CO-OPERATIVE BANK LTD
        public String RECORDSTATUS;	//Approved
        public String BRANCHDESC;	//LATUR DISTRICT CENTRAL CO-OPERATIVE BANK LTD
        public String AUX_PRTNR_BNK;
        public String ADDOFBRANCH;	//LATUR
        public String MICR;	//413801062
        public String IFSC;	//IBKL0497LDC
        public String BANKCODE;	//1073
        public String CITY;	//LTR
        public String BRANCHCODE;	//098817
        public String NPCI_BNK_DC_CODE;
        public String RECORD_ID;
        public String PCCITYNAME;	//LATUR
        public String AUX_BNK_NAME;	//LATUR DISTRICT CENTRAL CO-OPERATIVE BANK LTD
        public String NPCI_BNK_NETB_CODE;
        public String AUX_BNK_CODE;	//1073
    }
}